// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndkcghouhrizbifogozq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ka2NnaG91aHJpemJpZm9nb3pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQwODE3NTUsImV4cCI6MjA5OTY1Nzc1NX0.GtNyciCXga86dKKLLVigucaAevuC_xSIV2HZMzkqRPY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});